//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Booking
    {
        public int BookingID { get; set; }
        public Nullable<int> TaxiID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<System.DateTime> TripDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        [Required]
        [RegularExpression("^[A-Za-z]*$", ErrorMessage = "only Alphabets are allowed")]
        public string SourceAddress { get; set; }
        [Required]
        [RegularExpression("^[A-Za-z]*$", ErrorMessage = "only Alphabets are allowed")]
        public string DestinationAddress { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Taxi Taxi { get; set; }
    }
}
